import { Story } from './storyTypes'

export const mockStories: Story[] = [
  {
    id: 'story-1',
    title: 'Coffee Shop Order',
    context: 'You\'re at a local coffee shop. The barista is friendly but speaks quickly. You need to place an order for yourself and a friend.',
    tags: ['Daily Life', 'Service'],
    difficulty: 'easy',
    durationSec: 45,
    situation: 'Daily Life',
    clips: [
      {
        id: 'clip-1-1',
        startMs: 0,
        endMs: 8000,
        transcript: 'Can I get a large coffee with oat milk, please?',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-1-2',
        startMs: 8000,
        endMs: 16000,
        transcript: 'And a small latte, extra hot, no foam.',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
      {
        id: 'clip-1-3',
        startMs: 16000,
        endMs: 25000,
        transcript: 'That\'ll be twelve dollars and fifty cents.',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-1-4',
        startMs: 25000,
        endMs: 33000,
        transcript: 'Pay at the counter when you\'re ready.',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
    ],
  },
  {
    id: 'story-2',
    title: 'Office Meeting',
    context: 'You\'re in a team meeting discussing project deadlines. Your manager is updating everyone on the schedule and asking for feedback.',
    tags: ['Work', 'Professional'],
    difficulty: 'medium',
    durationSec: 90,
    situation: 'Work',
    clips: [
      {
        id: 'clip-2-1',
        startMs: 0,
        endMs: 12000,
        transcript: 'We need to push the deadline back by a week.',
        audioStatus: 'needs_generation',
        focusSkill: 'speed',
      },
      {
        id: 'clip-2-2',
        startMs: 12000,
        endMs: 24000,
        transcript: 'Can everyone make it to the follow-up meeting on Friday?',
        audioStatus: 'needs_generation',
        focusSkill: 'parsing',
      },
      {
        id: 'clip-2-3',
        startMs: 24000,
        endMs: 38000,
        transcript: 'I think we should discuss this with the client first.',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-2-4',
        startMs: 38000,
        endMs: 52000,
        transcript: 'Let\'s schedule a call for tomorrow afternoon.',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
      {
        id: 'clip-2-5',
        startMs: 52000,
        endMs: 65000,
        transcript: 'Sounds good, I\'ll send out the calendar invite.',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
    ],
  },
  {
    id: 'story-3',
    title: 'Asking for Directions',
    context: 'You\'re lost in a new city and need to find the train station. A local person is helping you with directions.',
    tags: ['Travel', 'Directions'],
    difficulty: 'medium',
    durationSec: 75,
    situation: 'Travel',
    clips: [
      {
        id: 'clip-3-1',
        startMs: 0,
        endMs: 10000,
        transcript: 'Excuse me, can you tell me how to get to the train station?',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-3-2',
        startMs: 10000,
        endMs: 22000,
        transcript: 'Sure, go straight for two blocks, then turn left at the traffic light.',
        audioStatus: 'needs_generation',
        focusSkill: 'speed',
      },
      {
        id: 'clip-3-3',
        startMs: 22000,
        endMs: 35000,
        transcript: 'You\'ll see it on your right, can\'t miss it.',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
      {
        id: 'clip-3-4',
        startMs: 35000,
        endMs: 47000,
        transcript: 'Thanks so much, I really appreciate it!',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
    ],
  },
  {
    id: 'story-4',
    title: 'Rescheduling Plans',
    context: 'You and a friend had plans to meet, but something came up. You need to reschedule and find a new time that works.',
    tags: ['Social', 'Planning'],
    difficulty: 'easy',
    durationSec: 55,
    situation: 'Social',
    clips: [
      {
        id: 'clip-4-1',
        startMs: 0,
        endMs: 9000,
        transcript: 'Hey, I\'m sorry but I can\'t make it tonight.',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-4-2',
        startMs: 9000,
        endMs: 20000,
        transcript: 'No worries, what about tomorrow instead?',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
      {
        id: 'clip-4-3',
        startMs: 20000,
        endMs: 32000,
        transcript: 'Tomorrow works great, same time and place?',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-4-4',
        startMs: 32000,
        endMs: 40000,
        transcript: 'Perfect, see you then!',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
    ],
  },
  {
    id: 'story-5',
    title: 'Restaurant Reservation',
    context: 'You\'re calling a restaurant to make a reservation for a special occasion. The host is checking availability.',
    tags: ['Travel', 'Service'],
    difficulty: 'medium',
    durationSec: 70,
    situation: 'Travel',
    clips: [
      {
        id: 'clip-5-1',
        startMs: 0,
        endMs: 11000,
        transcript: 'Hi, I\'d like to make a reservation for Friday evening.',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-5-2',
        startMs: 11000,
        endMs: 24000,
        transcript: 'For how many people, and what time were you thinking?',
        audioStatus: 'needs_generation',
        focusSkill: 'speed',
      },
      {
        id: 'clip-5-3',
        startMs: 24000,
        endMs: 37000,
        transcript: 'Two people, around seven o\'clock if possible.',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
      {
        id: 'clip-5-4',
        startMs: 37000,
        endMs: 50000,
        transcript: 'We have a table at seven-thirty, would that work?',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-5-5',
        startMs: 50000,
        endMs: 60000,
        transcript: 'That\'s perfect, thank you!',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
    ],
  },
  {
    id: 'story-6',
    title: 'Clarifying Instructions',
    context: 'Your colleague is explaining a new process at work. You need to ask clarifying questions to make sure you understand correctly.',
    tags: ['Work', 'Professional'],
    difficulty: 'hard',
    durationSec: 85,
    situation: 'Work',
    clips: [
      {
        id: 'clip-6-1',
        startMs: 0,
        endMs: 13000,
        transcript: 'So basically, you\'ll need to submit the report by end of day Thursday.',
        audioStatus: 'needs_generation',
        focusSkill: 'speed',
      },
      {
        id: 'clip-6-2',
        startMs: 13000,
        endMs: 27000,
        transcript: 'Just to clarify, do you mean this Thursday or next Thursday?',
        audioStatus: 'needs_generation',
        focusSkill: 'parsing',
      },
      {
        id: 'clip-6-3',
        startMs: 27000,
        endMs: 42000,
        transcript: 'This Thursday, and make sure you\'ve reviewed all the client feedback first.',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-6-4',
        startMs: 42000,
        endMs: 58000,
        transcript: 'Got it, I\'ll send it to you once I\'ve double-checked everything.',
        audioStatus: 'needs_generation',
        focusSkill: 'speed',
      },
      {
        id: 'clip-6-5',
        startMs: 58000,
        endMs: 72000,
        transcript: 'Perfect, let me know if you have any questions.',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
    ],
  },
  {
    id: 'story-7',
    title: 'Casual Invitation',
    context: 'You run into a friend and want to invite them to grab lunch. You\'re trying to find a time that works for both of you.',
    tags: ['Social', 'Invitation'],
    difficulty: 'easy',
    durationSec: 50,
    situation: 'Social',
    clips: [
      {
        id: 'clip-7-1',
        startMs: 0,
        endMs: 8000,
        transcript: 'Hey, wanna grab lunch this week?',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-7-2',
        startMs: 8000,
        endMs: 18000,
        transcript: 'Yeah, that sounds great! How about Wednesday?',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
      {
        id: 'clip-7-3',
        startMs: 18000,
        endMs: 30000,
        transcript: 'Wednesday works for me, where do you want to go?',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-7-4',
        startMs: 30000,
        endMs: 40000,
        transcript: 'There\'s that new Italian place downtown, wanna try it?',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
    ],
  },
  {
    id: 'story-8',
    title: 'Show Discussion',
    context: 'You and a coworker are talking about a TV show you both watch. You\'re discussing the latest episode and sharing opinions.',
    tags: ['Media', 'Social'],
    difficulty: 'medium',
    durationSec: 65,
    situation: 'Media',
    clips: [
      {
        id: 'clip-8-1',
        startMs: 0,
        endMs: 11000,
        transcript: 'Did you watch the latest episode yet?',
        audioStatus: 'needs_generation',
        focusSkill: 'reductions',
      },
      {
        id: 'clip-8-2',
        startMs: 11000,
        endMs: 24000,
        transcript: 'Yeah, I watched it last night, it was really intense!',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
      {
        id: 'clip-8-3',
        startMs: 24000,
        endMs: 38000,
        transcript: 'I know, right? That ending totally caught me off guard.',
        audioStatus: 'needs_generation',
        focusSkill: 'speed',
      },
      {
        id: 'clip-8-4',
        startMs: 38000,
        endMs: 50000,
        transcript: 'Same here, I can\'t wait to see what happens next week.',
        audioStatus: 'needs_generation',
        focusSkill: 'connected_speech',
      },
    ],
  },
]


